### ISSUE TITLE
Issue with Autosplit - stops splitting by itself

### ISSUE THREAD

**Issue by rubutik** [Zutatensuppe/DiabloInterface#42] opened 2018-12-02 01:23 UTC
My first three splits are the special game start, Black Marsh and outer cloister. The first split will automatically start when I run hit town after creating my character and the second split will trigger when I reach Black Marsh. After doing Countess runs for X period of time, I continue off, but at this point I no longer get the splits happening automatically. When I reach the outer cloister, the time keeps going with no update.

Wondering if there is a reason for this.

EDIT: After testing, it looks like quitting the game and logging back in is causing it to stop auto splitting anything it hasn't yet. Any work around for this?

**Comment by Zutatensuppe** [comment] 2018-12-03 09:57
thanks for investigating, sounds like a bug ... 

(i dont see a work around other than not closing the game OR closing diablo interface, but these are probably not very viable options?)

what version of DI are you using?

**Comment by rubutik** [comment] 2018-12-05 00:08
For the version, I am using whatever is the default in the link provided (I believe 0.4.3). 

Unfortunately I am regularly quitting the game and reloading the character for countess runs.

**Comment by viv-4** [comment] 2019-04-12 15:40
I'm seeing the same issue.

I set a Game Start split and Den Quest split.
If I start the game with a new char and go clear den it works as expected. 
If I start a game, leave game (save and quit to menu), then go back into game and go clear den it does not split at den.

To test further I then changed the auto split on Den Quest to auto split on Blood Moor Area and see the same behavior. Splits if I run straight out of town, does not split if I leave game, rejoin and run out of town.

It does however continue to update stats and fill in picked up runes after multiple rejoins, and even after completely closing and reopening D2.

It appears to me DI is losing visibility of the quests and areas on Save and Quit.

Diablo Interface 0.4.6 (current latest) - run as admin
LiveSplit 1.7.6 (current latest) - run as admin
Diablo II LOD 1.14D (current latest) - tested both run as admin and not

Having a bit of a read of the code it seems to me that the issue might be somewhere in [here](https://github.com/Zutatensuppe/DiabloInterface/blob/master/src/D2Reader/D2DataReader.cs) but I'm not seeing anything obvious to me for how it handles save and quit.

Hopefully all this is helpful :)

Happy to test further or provide any extra info needed, feel free to ping me in the Discord if I'm around.

Great project!

**Comment by Zutatensuppe** [comment] 2019-04-13 11:22
@qk4 Thanks for the detailed infos, ill try to reproduce + fix when I'm home! :+1:

**Closed** 2019-04-15 21:36 UTC
Labels: Bug

**Comment by Zutatensuppe** [comment] 2019-04-15 21:43
Fixed in [v0.4.7](https://github.com/Zutatensuppe/DiabloInterface/releases/tag/v0.4.7)

**Comment by agusmagne** [comment] 2021-05-03 10:46
Not related but how did you manage to get DI and LiveSplits to work together? I can't get the Game Start auto-split to start the clock when I create a new char

**Comment by Zutatensuppe** [comment] 2021-05-03 11:18
@agusmagne please check if you have a reset hotkey set up in diablo interface.
reset hotkey is just triggered directly before start hotkey, so livesplit may think it is an accidental double tap
to fix this, if you reset by hand anyway, you can unset(the reset hotkey)
or if you want to keep it, you can disble double tap prevention in the livesplit settings

i will add this to the troubleshooting section of readme later :)

**Comment by agusmagne** [comment] 2021-05-03 12:16
@Zutatensuppe Hey thanks for commenting so fast. I checked and on my Diablo Interface I don't have any key bound to 'Reset key' and just in case I deactivated the 'Double Tap prevention' in LiveSplits. I'm running both as Admin.

My LiveSplits splits are configured with 'Game Name' Diablo II: Lord Of Desctruction and I didn't set any Run Category. I added some splits like Andariel and stuff but I don't really know if I'm missing something. I also didn't find any guide on how to turn on the auto-splits on D2 with Diablo Interface and LiveSplits. If you think I'm missing something please let me know. Thanks

**Comment by Zutatensuppe** [comment] 2021-05-03 12:35
continuing here, because unrelated: #129
